### ISSUE TITLE
not working with Frodo

### ISSUE THREAD

**Issue by mgtiger** [brainwave9/SiriProxy-XBMC#10]
thanks for your work. I keep getting  "Did you configure the url and port for XBMC properly using Xbmc.base_uri 'http://localhost:1234" when trying to connect my system running Frodo

**Comment by Deanmv** [comment]
The commit here works up to Frodo RC3 https://github.com/brainwave9/SiriProxy-XBMC/commit/17738b52ee52f7ee8ed64f63aed7d6ae0d8700f3 all I can say is that is it configured in ~/.siriproxy/config.yml ?

**Comment by mgtiger** [comment]
sorry, I had the port information wrong. It connects now, but I'm getting the same error as shown in error 9 when trying to play a movie. thanks again
