### ISSUE TITLE
Nightlies/Frodo compatibility

### ISSUE THREAD

**Issue by invaderdag** [brainwave9/SiriProxy-XBMC#5]
I recently switched to using a nightly build of XBMC in order to get Airplay working, but I now can't get SiriProxy-XBMC to work. I believe it has to do with a change in the JSON-RPC API from v4 to v5, but I am not a programmer so I can't say for sure.

Is this something worth looking into at this time? I can provide the error messages and more details if so.

**Comment by brainwave9** [comment]
Should be ok now, I merged a pull request that fixes this
