### ISSUE TITLE
interface is down

### ISSUE THREAD

**Issue by wendelit** [brainwave9/SiriProxy-XBMC#6]
[SiriProxy-XBMC] An error occurred: A JSON text must at least contain two octets!
anyone knows why i get this error ?

**Comment by Deanmv** [comment]
In the latest nightlies (for Frodo) xbmc is changing their HTTP API and maybe updating their JSON implementation as well so probably something to do with that.

**Comment by wendelit** [comment]
Sorry i forgot to post it here. I dod find the solution: changed row 38 to:
    response = self.class.post('/jsonrpc', :body => {"jsonrpc" => "2.0", "params" => params, "id" => "1", "method" => method}.to_json,:headers => { 'Content-Type' => 'application/json' } )

**Comment by brainwave9** [comment]
I merged the pull request
