### ISSUE TITLE
XBMC 12.0 Error

### ISSUE THREAD

**Issue by jarrah31** [brainwave9/SiriProxy-XBMC#8]
When trying to control XBMC 12 beta, I receive the following error:

[SiriProxy-XBMC] An error occurred: A JSON text must at least contain two octets!

Control of XBMC 11 works fine, so I imagine there must be an API change somewhere?

Thanks

**Comment by Deanmv** [comment]
The API was changed between 11 and 12, I've not tested this recently (Siri Proxy is playing up) but last time I tried it this worked https://github.com/brainwave9/SiriProxy-XBMC/pull/7

**Comment by RaNaMaster** [comment]
this is what im getting

[SiriProxy-XBMC] Connecting to the XBMC interface (default)
[SiriProxy-XBMC] XBMC API Version {"major"=>6, "minor"=>0, "patch"=>0} - Eden
[SiriProxy-XBMC] Finding TV show (API version {"major"=>6, "minor"=>0, "patch"=>0})
/home/rana/.rvm/gems/ruby-1.9.3-p362@SiriProxy/bundler/gems/SiriProxy-XBMC-bc67ed6b36c8/lib/xbmc_library.rb:119:in `find_show': undefined method`each' for nil:NilClass (NoMethodError)
    from /home/rana/.rvm/gems/ruby-1.9.3-p362@SiriProxy/bundler/gems/SiriProxy-XBMC-bc67ed6b36c8/lib/siriproxy-xbmc.rb:144:in `block in <class:XBMC>'
    from /home/rana/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/cora-0.0.4/lib/cora/plugin.rb:47:in`instance_exec'
    from /home/rana/.rvm/gems/ruby-1.9.3-p362@SiriProxy/gems/cora-0.0.4/lib/cora/plugin.rb:47:in `block (2 levels) in process'
zlib(finalizer): the stream was freed prematurely.
zlib(finalizer): the stream was freed prematurely.

**Comment by Deanmv** [comment]
I fixed it with this: https://github.com/Deanmv/SiriProxy-XBMC/commit/bc67ed6b36c8e7275e0507109faebdb083678000

**Comment by brainwave9** [comment]
Merged. Thanks Deanmv !
